/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_org_jni_nativeutils
#define _Included_org_jni_nativeutils
#ifdef __cplusplus
extern "C" {
#endif
JNIEXPORT jstring JNICALL Java_org_jni_NativeUtils_Version(JNIEnv *, jclass obj);
JNIEXPORT jstring JNICALL Java_org_jni_NativeUtils_createObject(JNIEnv *env, jclass cls, jobject obj);
JNIEXPORT jstring JNICALL Java_org_jni_NativeUtils_deleteObject(JNIEnv *env, jclass cls, jobject obj);

JNIEXPORT void JNICALL Java_org_jni_NativeUtils_calibracionParam(JNIEnv *env, jclass cls, jobject obj, jint type, jint img_width, jint img_height, jint cx, jint cy, jdouble sx, jdouble sy, jdouble tx, jdouble ty, jdouble tz);

JNIEXPORT jstring JNICALL Java_org_jni_NativeUtils_genTriMesh2(JNIEnv *env, jclass cls, jobject obj, jshortArray jDepthY16);
JNIEXPORT jstring JNICALL Java_org_jni_NativeUtils_gen3DColorImage2(JNIEnv *env, jclass cls, jobject obj, jstring jFilePath, jstring jFile3dMainNameJpg, jstring jPicFileNameJpg, jint jpgWidth, jint jpgHeight);
JNIEXPORT jstring JNICALL Java_org_jni_NativeUtils_gen3DThermalImage2(JNIEnv *env, jclass cls, jobject obj, jstring jFilePath, jstring jFile3dMainNameThm, jstring jPicFileNamePng);
JNIEXPORT jstring JNICALL Java_org_jni_NativeUtils_calWoundAreaInfo2(JNIEnv *env, jclass cls, jobject obj, jstring jFilePath, jstring jPicFileNameJpg, jbyteArray jMaskY8, jint width, jint height, jint xx11, jint yy11, jint xx12, jint yy12, jint xx21, jint yy21, jint xx22, jint yy22);
JNIEXPORT jstring JNICALL Java_org_jni_NativeUtils_getThermalOnXY2(JNIEnv *env, jclass cls, jobject obj, int x, int y);


JNIEXPORT jstring JNICALL Java_org_jni_NativeUtils_nativeGetWoundInfo(JNIEnv *env, jclass cls, jobject obj, jstring jFilePath, jshortArray jDepthY16, jbyteArray jJPG888, jstring jFile3dMainName3ds, jstring jPicFileNameJpg, jfloatArray jThermalY32, jbyteArray jPNG888, jstring jFile3dMainNameThm, jstring jPicFileNamePng, jbyteArray jMaskY8, jint width, jint height, jint xx11, jint yy11, jint xx12, jint yy12, jint xx21, jint yy21, jint xx22, jint yy22, jboolean save);
JNIEXPORT jstring JNICALL Java_org_jni_NativeUtils_nativeGen3DColorImage (JNIEnv *env, jclass cls, jobject obj, jstring jFilePath, jstring jFile3dMainName, jstring jPicFileName, jshortArray jDepthY16, jbyteArray jRGB888, jint width, jint height, jlong addrDstImage);
JNIEXPORT jstring JNICALL Java_org_jni_NativeUtils_nativeGen3DThermalImage (JNIEnv *env, jclass cls, jobject obj, jstring jFilePath, jstring jFile3dMainName, jstring jPicFileName, jshortArray jDepthY16, jfloatArray jThermalY32, jbyteArray jRGB888, jint width, jint height, jlong addrDstImage);

#ifdef __cplusplus
}
#endif
#endif
